import turtle as tle
tle.pensize(5)
tle.speed(15)
tle.bgcolor("black")
tle.color("black")
tle.left(180)
tle.forward(250)
tle.left(180)
tle.left(90)
tle.forward(150)
tle.right(90)
for i in range(15):
    tle.color("orange")
    tle.forward(500)
    tle.right(90)
    tle.forward(3)
    tle.right(90)
    tle.forward(500)
    tle.left(90)
    tle.forward(3)
    tle.left(90)
for i in range(15):
    tle.color("white")
    tle.forward(500)
    tle.right(90)
    tle.forward(3)
    tle.right(90)
    tle.forward(500)
    tle.left(90)
    tle.forward(3)
    tle.left(90)
for i in range(15):
    tle.color("green")
    tle.forward(500)
    tle.right(90)
    tle.forward(3)
    tle.right(90)
    tle.forward(500)
    tle.left(90)
    tle.forward(3)
    tle.left(90)
for i in range(5):
    tle.color("brown")
    tle.right(90)
    tle.forward(500)
    tle.left(90)
    tle.forward(3)
    tle.left(90)
    tle.forward(500)
    tle.right(90)
    tle.forward(3)
tle.right(180)
tle.forward(30)
tle.color("green")
tle.right(90)
tle.forward(90)
tle.color("white")
tle.forward(10)
tle.right(90)
tle.forward(250)
tle.pensize(2)
tle.color("black")
tle.circle(35)
tle.left(90)
tle.forward(35)
for i in range(28):
    tle.left(12.9)
    tle.forward(35)
    tle.left(180)
    tle.forward(35)
tle.hideturtle()


